###

GET http://localhost/solicitudes/ HTTP/1.1

###
GET http://localhost/usuarios/autenticar HTTP/1.1
Content-Type: application/json

{
    "CorreoUsuario": "test24@example.com",
    "ContrasenaUsuario": "admin123"
}

###

GET http://localhost/programaciones/4 HTTP/1.1

###

POST http://localhost/solicitudes/ HTTP/1.1
Content-Type: application/json

{
    "ComentarioSolicitud": "testing",
    "ClienteId": 1,
    "ServicioId": 3
}

###

###

DELETE http://localhost/clientes/35 HTTP/1.1

###

PUT http://localhost/solicitudes/29 HTTP/1.1 
Content-Type: application/json

{
    "FechaSolicitud": "2024-07-21T18:09:29.128Z",
    "FechaCita": "2024-07-20T18:09:29.128Z",
    "ComentarioSolicitud": "testing Fer",
    "ClienteId": 1,
    "ServicioId": 3
}