###

GET http://localhost/usuarios/ HTTP/1.1

###
GET http://localhost/usuarios/autenticar HTTP/1.1
Content-Type: application/json

{
    "CorreoUsuario": "test24@example.com",
    "ContrasenaUsuario": "admin123"
}

###

GET http://localhost/programaciones/4 HTTP/1.1

###

POST http://localhost/usuarios/ HTTP/1.1
Content-Type: application/json

{
  
   "NombreUsuario": "Fernanda Jarquin",
    "CorreoUsuario": "test24@example.com",
    "ContrasenaUsuario": "$2b$10$2/EIOFcpD3CTniAgH.0ZX.0DXuQM48hGkNipxx5DQV2Ol9Ts4/RbW",
    "Rol": "Administrador"
  
}

###

DELETE http://localhost/clientes/36 HTTP/1.1
 
###

PUT http://localhost/usuario/1 HTTP/1.1 
Content-Type: application/json

{
  "Accion": "TEST (V3)",
}